Repository tine20/tine20, pull requests merged in 2018-06, with the labels that each got.

#80 test(Addressbook): adds more Addressbook tests to Travis test suite
  tests/tine20/TravisTests.php
Labels: Addressbook

#6862 test(Calendar): adds all Calendar test suite to travisci tests
  tests/tine20/TravisTests.php
Labels: Unittests

#6865 test(Travis): updates travis config
  .travis.yml
  tine20/config.inc.travis.php
  tine20/install.properties.travis
Labels: Unittests

#6866 test(Calendar): skip testModLogUndo when running via travis-ci
  tests/tine20/Calendar/Controller/EventTests.php
Labels: Calendar, Unittests

#6867 test(Calendar): skip testRruleModLogUndo when running via travis-ci
  tests/tine20/Calendar/Controller/EventTests.php
Labels: Calendar, Unittests

#6868 test(Calendar): skip testExternalInvitationRequestMultiImport
  tests/tine20/Calendar/Frontend/iMIPTest.php
Labels: Unittests

#6878 tine20-6876 2018.08.1: Shared folder - Error in property dialog
  tine20/Tinebase/js/widgets/container/GrantsGrid.js
Labels: Bug, Tinebase JavaScript
